In [1]:
#Run this cell first
import numpy as np
import pandas as pd
import plotly.express as px

**Quiz1**

นาย A,B,C,D,E มีรายได้ 10,000 20,000 30,000 40,000 60,000 ต่อเดือนในปี 2020 ตามลำดับ ทุกๆปีเงินเดือนจะเพิ่ม 7% จงสร้าง DataFrame เก็บเงินเดือนของทั้ง 5 นาย ในปี 2016,2017,2018,2019,2020 

In [60]:
#Is not done.!
year = ['2016', '2017', '2018', '2019', '2020']
name = ['A', 'B', 'C', 'D', 'E']
salary = [10000, 20000, 30000, 40000, 600000]
Values = []

for i in range(4):
  salary = list(map(lambda x:round(x/1.07,2),salary))
  Values.append(salary)
salary = [10000, 20000, 30000, 40000, 600000]
Values.append(salary)
print(np.array(Values))


#print(values.T)


#df = pd.DataFrame(Values, name, year)
#df.T


[[  9345.79  18691.59  28037.38  37383.18 560747.66]
 [  8734.38  17468.78  26203.16  34937.55 524063.23]
 [  8162.97  16325.96  24488.93  32651.92 489778.72]
 [  7628.94  15257.91  22886.85  30515.81 457737.12]
 [ 10000.    20000.    30000.    40000.   600000.  ]]


In [ ]:
!wget https://gist.githubusercontent.com/deen666/aaf734fe721ca1bf504d324bf76eef04/raw/8f990dffacaf13cff911a86d4bc944be3b0d0486/train.csv

In [ ]:
ls

sample_data/  train.csv
