1. จงเขียน array ที่มีแต่เลข 0 แบบ vector 10 ตัว และ แบบ Matrix 4x4

2. จงเขียน array ที่มีแต่เลข 1 แบบ vector 5 ตัว และ แบบ Matrix 3x3

3. จงเขียน array ที่มีเป็นการ random ตัวเลข 20 ตัว แบบ float ค่าอยู่ในช่วง 10-99 แล้วนำแต่ละเลขยกกำลังสอง

4. ทำเหมือนข้อ 3 แต่เขียนแบบ List comprehension

5. นำข้อ 3 และ 4 มาเปรียบเวลากัน โดยใช้ฟังก์ชั่น time.time( ) เพื่อจับเวลา แสดงผลลัพธ์ในรูปแบบมิลลิวินาที

6. จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลข 10 ถึง 1000  

7. จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคู่ 10 ถึง 2000 

8. จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคี่ 12 ถึง 900

9. จงสร้าง identity matrix แบบ 4x4

10. จงหาว่า array ที่มีสมาชิก 100 ตัว เริ่มจาก 5 ถึง 25 มีผลต่างแต่ละตัวเท่ากับเท่าใด

11. จงเขียนฟังก์ชั่น random ตัวเลขแบบ float ในช่วง 0-1 ขึ้นมา 1 ตัว

12. จงเขียนฟังก์ชั่นที่ random ตัวเลขแบบ int ในช่วง 50-100 โดยให้อยู่ในรูป Matrix 4x4 และ Transpose

13. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 8,9,13,14 

14. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 18,19,20

15. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 16,17,21,22

16. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกทั้งแถว 3

17. จงเขียนโค้ดที่ทำให้ได้ array นี้ออกมา

18. จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ If-else เช็คทีละตัวว่าตัวใดบ้างที่มีค่ามากกว่า
      50 และปริ้นออกมา

19. จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ conditional selection เช็คว่าตัวใดบ้างมีค่า  
      มากกว่า 40 นำมาใส่ List ที่สร้างใหม่ และปริ้นออกมา

20. เขียนโปรแกรมรับค่าจากผู้ใช้ให้ป้อนเลข 9 ตัว แต่ละตัวต้องไม่ซ้ำกันและมีค่าอยู่ในช่วง 10-100 นำเลข 9 ตัวนั้นมาทำเป็น matrix 
      3x3 และ transport และหาเลขอยู่ตำแหน่งที่ (2,2)


**Quiz1**

จงเขียน array ที่มีแต่เลข 0 แบบ vector 10 ตัว และ แบบ Matrix 4x4

In [0]:
import numpy as np

In [5]:
print(np.zeros(10))
print(np.zeros((4,4)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Quiz2**

จงเขียน array ที่มีแต่เลข 1 แบบ vector 5 ตัว และ แบบ Matrix 3x3

In [6]:
print(np.ones(5))
print(np.ones((3,3)))

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**Quiz3**

จงเขียน array ที่มีเป็นการ random ตัวเลข 20 ตัว แบบ float ค่าอยู่ในช่วง 10-99 แล้วนำแต่ละเลขยกกำลังสอง

In [50]:
x, y = 10, 99
rand20 = (y-x)*np.random.rand(20) + x
power2 = rand20 ** 2
print('Random 20 numbers between 10 and 99\n',rand20)
print('Then power of 2!\n',power2)

Random 20 numbers between 10 and 99
 [77.04911531 68.17963467 79.76078391 81.62196031 53.46792772 79.45497481
 52.43962538 42.90998491 24.57075597 23.23586781 41.38501704 98.78272491
 39.26272074 62.39301292 82.57688789 17.83236766 94.86385719 55.36703037
 41.63182841 90.97690033]
Then power of 2!
 [5936.56616936 4648.46258404 6361.78264956 6662.14440435 2858.81929477
 6313.09302285 2749.91431048 1841.26680489  603.722049    539.90555266
 1712.71963514 9758.0267409  1541.56124005 3892.88806135 6818.94241386
  317.9933364  8999.15140019 3065.50805224 1733.20913644 8276.79639341]
