#To-do
4. ทำเหมือนข้อ 3 แต่เขียนแบบ List comprehension

5. นำข้อ 3 และ 4 มาเปรียบเวลากัน โดยใช้ฟังก์ชั่น time.time( ) เพื่อจับเวลา แสดงผลลัพธ์ในรูปแบบมิลลิวินาที

6. จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลข 10 ถึง 1000  

7. จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคู่ 10 ถึง 2000 

8. จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคี่ 12 ถึง 900

9. จงสร้าง identity matrix แบบ 4x4

10. จงหาว่า array ที่มีสมาชิก 100 ตัว เริ่มจาก 5 ถึง 25 มีผลต่างแต่ละตัวเท่ากับเท่าใด

11. จงเขียนฟังก์ชั่น random ตัวเลขแบบ float ในช่วง 0-1 ขึ้นมา 1 ตัว

12. จงเขียนฟังก์ชั่นที่ random ตัวเลขแบบ int ในช่วง 50-100 โดยให้อยู่ในรูป Matrix 4x4 และ Transpose

13. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 8,9,13,14 

14. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 18,19,20

15. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 16,17,21,22

16. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกทั้งแถว 3

17. จงเขียนโค้ดที่ทำให้ได้ array นี้ออกมา

18. จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ If-else เช็คทีละตัวว่าตัวใดบ้างที่มีค่ามากกว่า
      50 และปริ้นออกมา

19. จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ conditional selection เช็คว่าตัวใดบ้างมีค่า  
      มากกว่า 40 นำมาใส่ List ที่สร้างใหม่ และปริ้นออกมา

20. เขียนโปรแกรมรับค่าจากผู้ใช้ให้ป้อนเลข 9 ตัว แต่ละตัวต้องไม่ซ้ำกันและมีค่าอยู่ในช่วง 10-100 นำเลข 9 ตัวนั้นมาทำเป็น matrix 
      3x3 และ transport และหาเลขอยู่ตำแหน่งที่ (2,2)


**Quiz1**

จงเขียน array ที่มีแต่เลข 0 แบบ vector 10 ตัว และ แบบ Matrix 4x4

In [0]:
import numpy as np

In [0]:
print(np.zeros(10))
print(np.zeros((4,4)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Quiz2**

จงเขียน array ที่มีแต่เลข 1 แบบ vector 5 ตัว และ แบบ Matrix 3x3

In [0]:
print(np.ones(5))
print(np.ones((3,3)))

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**Quiz3**

จงเขียน array ที่มีเป็นการ random ตัวเลข 20 ตัว แบบ float ค่าอยู่ในช่วง 10-99 แล้วนำแต่ละเลขยกกำลังสอง

In [5]:
x, y = 10, 99
rand20 = (np.random.rand(20)*(y-x)) + x
power2 = rand20 ** 2
print('Random 20 numbers between 10 and 99\n',rand20)
print('Then power of 2!\n',power2)

Random 20 numbers between 10 and 99
 [33.50362632 41.3039099  58.60449497 35.77145477 90.52483258 74.05057647
 98.70658265 41.40788944 77.31012226 51.81193913 20.43541012 23.48749463
 67.63313745 15.95030317 88.95546559 70.24215277 65.68888474 22.25248814
 29.24229663 14.50813361]
Then power of 2!
 [1122.49297661 1706.01297319 3434.48683084 1279.59697641 8194.74531297
 5483.48787518 9742.98945924 1714.61330785 5976.85500381 2684.47703668
  417.60598684  551.66240401 4574.24128193  254.41217115 7913.07485889
 4933.96002563 4315.02957796  495.17322827  855.11191214  210.48594074]
