**Quiz1**

จงเขียน array ที่มีแต่เลข 0 แบบ vector 10 ตัว และ แบบ Matrix 4x4

In [0]:
#run this cell first.
import numpy as np
import random
import array as arr
import time

In [0]:
#Quiz1
print(np.zeros(10))
print(np.zeros((4,4)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Quiz2**

จงเขียน array ที่มีแต่เลข 1 แบบ vector 5 ตัว และ แบบ Matrix 3x3

In [0]:
#Quiz2
print(np.ones(5))
print(np.ones((3,3)))

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**Quiz3**

จงเขียน array ที่มีเป็นการ random ตัวเลข 20 ตัว แบบ float ค่าอยู่ในช่วง 10-99 แล้วนำแต่ละเลขยกกำลังสอง

In [0]:
#Quiz3
#test
rand_id1 = np.random.uniform(10,100,20)
print('Random 20 numbers between 10 and 99\n',rand_id1)
print('Then power of 2!\n',rand_id1**2)

Random 20 numbers between 10 and 99
 [80.59422824 31.91214393 66.83840975 44.74371363 20.09628557 69.80145105
 91.0896967  28.24413137 33.95819725 85.47090264 76.22851334 57.53837388
 82.86449829 15.59566516 85.27242036 41.46969777 24.98594898 88.6774883
 60.96552916 76.63057781]
Then power of 2!
 [6495.42962489 1018.38493028 4467.37301768 2001.99990905  403.86069365
 4872.24256866 8297.33284574  797.73095702 1153.15916077 7305.27519768
 5810.78624556 3310.66446923 6866.52507731  243.2247718  7271.38567417
 1719.73583299  624.29764668 7863.6969318  3716.79574529 5872.24545497]


In [0]:
#Quiz3
x, y = 10, 99
rand20 = (np.random.rand(20)*(y-x)) + x
power2 = rand20 ** 2
print('Random 20 numbers between 10 and 99\n',rand20)
print('Then power of 2!\n',power2)

Random 20 numbers between 10 and 99
 [33.50362632 41.3039099  58.60449497 35.77145477 90.52483258 74.05057647
 98.70658265 41.40788944 77.31012226 51.81193913 20.43541012 23.48749463
 67.63313745 15.95030317 88.95546559 70.24215277 65.68888474 22.25248814
 29.24229663 14.50813361]
Then power of 2!
 [1122.49297661 1706.01297319 3434.48683084 1279.59697641 8194.74531297
 5483.48787518 9742.98945924 1714.61330785 5976.85500381 2684.47703668
  417.60598684  551.66240401 4574.24128193  254.41217115 7913.07485889
 4933.96002563 4315.02957796  495.17322827  855.11191214  210.48594074]


**Quiz4**

ทำเหมือนข้อ 3 แต่เขียนแบบ List comprehension

In [0]:
import array as arr

In [150]:
#Quiz4
y = []
for i in range(20):
    x = random.uniform(10,100)
    y.append(x)

power_2 = [i**2 for i in y]


print('Random 20 numbers between 10 and 99\n',list(y))
print('Then power of 2!\n',power_2)

Random 20 numbers between 10 and 99
 [87.34748627878119, 90.5631903203547, 88.43776384833774, 41.904374470448005, 50.27550578511711, 28.051714728434266, 69.00570784063956, 45.77023082848371, 35.93262352528481, 46.701674109613336, 66.72512884644524, 60.968270914960556, 75.25559732626482, 62.163567560323486, 87.44256266688511, 67.65566896081259, 74.04774869358093, 84.67238943270273, 13.360990119429044, 34.793434437528205]
Then power of 2!
 [7629.583359221869, 8201.691441000788, 7821.238074494353, 1755.9765997595346, 2527.626481949344, 786.898699205456, 4761.787714587704, 2094.9140300926806, 1291.1534334098515, 2181.0463646405287, 4452.242819574719, 3717.130058360025, 5663.404928932917, 3864.3091318269026, 7646.201765752129, 4577.28954253506, 5483.069086587716, 7169.4135322432685, 178.51605697148054, 1210.5830799585738]


In [0]:
#test
rand_lst2 = np.random.uniform(10,100,20)
power_2 = [i**2 for i in rand_lst2]

print('Random 20 numbers between 10 and 99\n',rand_lst2)
print('Then power of 2!\n',power_2)


Random 20 numbers between 10 and 99
 [52.44027037 37.53286109 13.46652399 47.36304194 88.34374435 92.2708094
 98.68479504 64.85738523 56.48267243 86.1661702  32.59087126 14.93592569
 10.50218181 35.64923408 38.72449765 50.71802949 58.08278835 88.87419911
 49.25504947 20.44413292]
Then power of 2!
 [2749.9819563452734, 1408.715661634146, 181.34726837864406, 2243.257741730497, 7804.617165524886, 8513.902267046746, 9738.688772857075, 4206.480419039017, 3190.2922845405947, 7424.608887235089, 1062.1648894339357, 223.08187610521261, 110.2958226917081, 1270.8678904743865, 1499.5867181557107, 2572.318515564471, 3373.6103020567953, 7898.623267958072, 2426.059897918432, 417.9625707205596]


 **Quiz5**

 นำข้อ 3 และ 4 มาเปรียบเวลากัน โดยใช้ฟังก์ชั่น time.time( ) เพื่อจับเวลา แสดงผลลัพธ์ในรูปแบบมิลลิวินาที

In [0]:
import time

In [215]:
#Quiz5

#checking time from Quiz3
x, y = 10, 99
rand20 = np.random.rand(20)*(y-x) + x 
time1 = time.time() * 1000
rand20_power2 = rand20 ** 2
time2 = time.time() * 1000
quiz3_timing = time2-time1
print(quiz3_timing)


#test
#%timeit -n1000 rand20_power2
#millis1 = int(time.time() * 1000)
#print(millis1)

0.04833984375
1000 loops, best of 3: 18.4 ns per loop


In [218]:
#Quiz5

#checking time from Quiz4
y = []

for i in range(20):
    x = random.uniform(10,100)
    y.append(x)

time2 = time.time() * 1000
power_2 = [i**2 for i in y]
time3 = time.time() * 1000
quiz4_timing = time3-time2
print(quiz4_timing)


#test
#%timeit -n1000 power_2
#millis2 = int(time.time() * 1000)
#print(millis1)
#print(millis2)
print('Compare timing between Quiz3 {} and Quiz4 {} diff = '.format(quiz3_timing,quiz4_timing),quiz4_timing-quiz3_timing)

0.160888671875
Compare timing between Quiz3 0.04833984375 and Quiz4 0.160888671875 diff =  0.112548828125


**Quiz6**

จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลข 10 ถึง 1000  

In [48]:
#Quiz6
arr2 = np.arange(10,1001)
print(arr2)
#print(arr2.shape)

[  10   11   12   13   14   15   16   17   18   19   20   21   22   23
   24   25   26   27   28   29   30   31   32   33   34   35   36   37
   38   39   40   41   42   43   44   45   46   47   48   49   50   51
   52   53   54   55   56   57   58   59   60   61   62   63   64   65
   66   67   68   69   70   71   72   73   74   75   76   77   78   79
   80   81   82   83   84   85   86   87   88   89   90   91   92   93
   94   95   96   97   98   99  100  101  102  103  104  105  106  107
  108  109  110  111  112  113  114  115  116  117  118  119  120  121
  122  123  124  125  126  127  128  129  130  131  132  133  134  135
  136  137  138  139  140  141  142  143  144  145  146  147  148  149
  150  151  152  153  154  155  156  157  158  159  160  161  162  163
  164  165  166  167  168  169  170  171  172  173  174  175  176  177
  178  179  180  181  182  183  184  185  186  187  188  189  190  191
  192  193  194  195  196  197  198  199  200  201  202  203  204  205
  206 

**Quiz7**

จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคู่ 10 ถึง 2000

In [50]:
#Quiz7
arr2 = np.arange(10,1001,2)
print(arr2)
#print(arr2.shape)

[  10   12   14   16   18   20   22   24   26   28   30   32   34   36
   38   40   42   44   46   48   50   52   54   56   58   60   62   64
   66   68   70   72   74   76   78   80   82   84   86   88   90   92
   94   96   98  100  102  104  106  108  110  112  114  116  118  120
  122  124  126  128  130  132  134  136  138  140  142  144  146  148
  150  152  154  156  158  160  162  164  166  168  170  172  174  176
  178  180  182  184  186  188  190  192  194  196  198  200  202  204
  206  208  210  212  214  216  218  220  222  224  226  228  230  232
  234  236  238  240  242  244  246  248  250  252  254  256  258  260
  262  264  266  268  270  272  274  276  278  280  282  284  286  288
  290  292  294  296  298  300  302  304  306  308  310  312  314  316
  318  320  322  324  326  328  330  332  334  336  338  340  342  344
  346  348  350  352  354  356  358  360  362  364  366  368  370  372
  374  376  378  380  382  384  386  388  390  392  394  396  398  400
  402 

**Quiz8**

จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคี่ 12 ถึง 900

In [71]:
#Quiz8
arr2 = np.arange(12, 901) 
#arr2%2 == 1   check bool
arr2[arr2%2 == 1]

#print(arr2.shape)

array([ 13,  15,  17,  19,  21,  23,  25,  27,  29,  31,  33,  35,  37,
        39,  41,  43,  45,  47,  49,  51,  53,  55,  57,  59,  61,  63,
        65,  67,  69,  71,  73,  75,  77,  79,  81,  83,  85,  87,  89,
        91,  93,  95,  97,  99, 101, 103, 105, 107, 109, 111, 113, 115,
       117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139, 141,
       143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167,
       169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191, 193,
       195, 197, 199, 201, 203, 205, 207, 209, 211, 213, 215, 217, 219,
       221, 223, 225, 227, 229, 231, 233, 235, 237, 239, 241, 243, 245,
       247, 249, 251, 253, 255, 257, 259, 261, 263, 265, 267, 269, 271,
       273, 275, 277, 279, 281, 283, 285, 287, 289, 291, 293, 295, 297,
       299, 301, 303, 305, 307, 309, 311, 313, 315, 317, 319, 321, 323,
       325, 327, 329, 331, 333, 335, 337, 339, 341, 343, 345, 347, 349,
       351, 353, 355, 357, 359, 361, 363, 365, 367, 369, 371, 37

**Quiz9**

จงสร้าง identity matrix แบบ 4x4

In [76]:
#Quiz9
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Quiz10**

จงหาว่า array ที่มีสมาชิก 100 ตัว เริ่มจาก 5 ถึง 25 มีผลต่างแต่ละตัวเท่ากับเท่าใด

In [75]:
#Quiz10
arr2 = np.linspace(5,25,100)
print(arr2)

#print('Diff = ', arr2[1]-arr2[0])
print('Diff = ', np.diff(arr2))

[ 5.          5.2020202   5.4040404   5.60606061  5.80808081  6.01010101
  6.21212121  6.41414141  6.61616162  6.81818182  7.02020202  7.22222222
  7.42424242  7.62626263  7.82828283  8.03030303  8.23232323  8.43434343
  8.63636364  8.83838384  9.04040404  9.24242424  9.44444444  9.64646465
  9.84848485 10.05050505 10.25252525 10.45454545 10.65656566 10.85858586
 11.06060606 11.26262626 11.46464646 11.66666667 11.86868687 12.07070707
 12.27272727 12.47474747 12.67676768 12.87878788 13.08080808 13.28282828
 13.48484848 13.68686869 13.88888889 14.09090909 14.29292929 14.49494949
 14.6969697  14.8989899  15.1010101  15.3030303  15.50505051 15.70707071
 15.90909091 16.11111111 16.31313131 16.51515152 16.71717172 16.91919192
 17.12121212 17.32323232 17.52525253 17.72727273 17.92929293 18.13131313
 18.33333333 18.53535354 18.73737374 18.93939394 19.14141414 19.34343434
 19.54545455 19.74747475 19.94949495 20.15151515 20.35353535 20.55555556
 20.75757576 20.95959596 21.16161616 21.36363636 21

**Quiz11**

จงเขียนฟังก์ชั่น random ตัวเลขแบบ float ในช่วง 0-1 ขึ้นมา 1 ตัว

*จากโจทย์ข้อนี้ไม่แน่ใจให้เขียนเป็นฟังก์ชั่นเพื่อใช้ออกมา หรือว่าใช้ฟังก์ชั่นที่มีอยู่แล้ว จึงเขียนทั้ง2แบบ*

In [99]:
#Quiz11
np.random.rand(1)

array([0.82272788])

In [87]:
#Quiz11
def RandomFloat():
    a = np.random.rand(1)
    return a[0]

RandomFloat()

0.5752314836296449

**Quiz12**

จงเขียนฟังก์ชั่นที่ random ตัวเลขแบบ int ในช่วง 50-100 โดยให้อยู่ในรูป Matrix 4x4 และ Transpose

In [97]:
#Quiz12
arr2 = np.random.randint(50,100,16)
print(arr2)
arr2 = arr2.reshape(4,4)
print(arr2)
arr2 = arr2.T
print(arr2)

[60 59 72 84 73 79 75 60 84 73 61 72 50 83 89 63]
[[60 59 72 84]
 [73 79 75 60]
 [84 73 61 72]
 [50 83 89 63]]
[[60 73 84 50]
 [59 79 73 83]
 [72 75 61 89]
 [84 60 72 63]]


**Quiz13-17**

13. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 8,9,13,14 

14. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 18,19,20

15. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 16,17,21,22

16. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกทั้งแถว 3

17. จงเขียนโค้ดที่ทำให้ได้ array นี้ออกมา


In [0]:
#Preparing a variable for Quiz13-17
arr2 = np.arange(1,26)
arr2.reshape(5,5)
arr2 = arr2.reshape(5,5)

In [116]:
#Quiz13
arr2[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

In [117]:
#Quiz14
arr2[3,2:]

array([18, 19, 20])

In [118]:
#Quiz15
arr2[3:,:2]

array([[16, 17],
       [21, 22]])

In [124]:
#Quiz16
arr2[2]

array([11, 12, 13, 14, 15])

In [119]:
#Quiz17
arr2 = np.arange(1,26)
arr2.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Quiz18**

จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ If-else เช็คทีละตัวว่าตัวใดบ้างที่มีค่ามากกว่า
      50 และปริ้นออกมา

In [131]:
#Quiz18
arr2 = np.random.randint(10,100,(5,5))
print(arr2)
arr2 = arr2[arr2>50]
print(arr2)

[[27 97 83 39 84]
 [92 78 41 54 69]
 [60 12 50 92 98]
 [99 33 42 88 16]
 [73 84 28 17 68]]
[97 83 84 92 78 54 69 60 92 98 99 88 73 84 68]


In [135]:
#Quiz18 (ใช้ if-else ?)
arr2 = np.random.randint(10,100,(5,5))
count = len(arr2)
countin = len(arr2[0])
print(arr2)

i = 0
for i in range(count):
  for j in range(countin):
    if arr2[i][j] > 50:
      print(arr2[i][j])
    

[[10 56 81 32 70]
 [20 48 15 74 71]
 [66 43 29 28 33]
 [54 87 48 41 99]
 [26 55 87 67 22]]
56
81
70
74
71
66
54
87
99
55
87
67


**Quiz19**

จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ conditional selection เช็คว่าตัวใดบ้างมีค่า  
      มากกว่า 40 นำมาใส่ List ที่สร้างใหม่ และปริ้นออกมา


In [149]:
#Quiz19
arr2 = np.random.randint(10,100,(5,5))
print(arr2)

filtered_arr = arr2[arr2>40]
print(list(filtered_arr)) 

[[70 84 75 30 11]
 [90 12 73 12 34]
 [14 87 80 25 27]
 [76 31 61 74 12]
 [58 37 12 74 64]]
[70, 84, 75, 90, 73, 87, 80, 76, 61, 74, 58, 74, 64]


In [146]:
#Quiz19
arr2 = np.random.randint(10,100,(5,5))
count = len(arr2)
countin = len(arr2[0])
print(arr2)

lst = []
i = 0
for i in range(count):
  for j in range(countin):
    if arr2[i][j] > 40:
      lst.append(arr2[i][j])
      
print(lst)

[[98 62 29 28 50]
 [82 99 53 13 35]
 [62 25 73 78 90]
 [56 98 77 50 10]
 [87 25 45 31 65]]
[98, 62, 50, 82, 99, 53, 62, 73, 78, 90, 56, 98, 77, 50, 87, 45, 65]


**Quiz20**

เขียนโปรแกรมรับค่าจากผู้ใช้ให้ป้อนเลข 9 ตัว แต่ละตัวต้องไม่ซ้ำกันและมีค่าอยู่ในช่วง 10-100 นำเลข 9 ตัวนั้นมาทำเป็น matrix 
      3x3 และ transport และหาเลขอยู่ตำแหน่งที่ (2,2)


In [244]:
lst = []

while (len(lst) < 9):
  print('Enter a number between 10-100:')
  num = (int(input()))
  if (num >= 10) and (num <= 100) and (num not in lst):
    lst.append(num)
    print(lst)
  elif len(lst) == 9: 
    break
  else: 
    print('The number',num ,'is not between 10 and 100 or is a duplicate in the list.\nPlease try again')

arr = np.array(lst)
arr = arr.reshape(3,3)
print('Matrix 3x3 from the list is\n',arr,'\n')
arr = arr.T
print('Transpose\n',arr)


Enter a number between 10-100:
666
The number 666 is not between 10 and 100 or is a duplicate in the list.
Please try again
Enter a number between 10-100:
10
[10]
Enter a number between 10-100:
20
[10, 20]
Enter a number between 10-100:
30
[10, 20, 30]
Enter a number between 10-100:
40
[10, 20, 30, 40]
Enter a number between 10-100:
50
[10, 20, 30, 40, 50]
Enter a number between 10-100:
66
[10, 20, 30, 40, 50, 66]
Enter a number between 10-100:
66
The number 66 is not between 10 and 100 or is a duplicate in the list.
Please try again
Enter a number between 10-100:
77
[10, 20, 30, 40, 50, 66, 77]
Enter a number between 10-100:
88
[10, 20, 30, 40, 50, 66, 77, 88]
Enter a number between 10-100:
99
[10, 20, 30, 40, 50, 66, 77, 88, 99]
Matrix 3x3 is
 [[10 20 30]
 [40 50 66]
 [77 88 99]] 

Transpose
 [[10 40 77]
 [20 50 88]
 [30 66 99]]
