#To-do
6. จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลข 10 ถึง 1000  

7. จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคู่ 10 ถึง 2000 

8. จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคี่ 12 ถึง 900

9. จงสร้าง identity matrix แบบ 4x4

10. จงหาว่า array ที่มีสมาชิก 100 ตัว เริ่มจาก 5 ถึง 25 มีผลต่างแต่ละตัวเท่ากับเท่าใด

11. จงเขียนฟังก์ชั่น random ตัวเลขแบบ float ในช่วง 0-1 ขึ้นมา 1 ตัว

12. จงเขียนฟังก์ชั่นที่ random ตัวเลขแบบ int ในช่วง 50-100 โดยให้อยู่ในรูป Matrix 4x4 และ Transpose

13. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 8,9,13,14 

14. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 18,19,20

15. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 16,17,21,22

16. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกทั้งแถว 3

17. จงเขียนโค้ดที่ทำให้ได้ array นี้ออกมา

18. จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ If-else เช็คทีละตัวว่าตัวใดบ้างที่มีค่ามากกว่า
      50 และปริ้นออกมา

19. จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ conditional selection เช็คว่าตัวใดบ้างมีค่า  
      มากกว่า 40 นำมาใส่ List ที่สร้างใหม่ และปริ้นออกมา

20. เขียนโปรแกรมรับค่าจากผู้ใช้ให้ป้อนเลข 9 ตัว แต่ละตัวต้องไม่ซ้ำกันและมีค่าอยู่ในช่วง 10-100 นำเลข 9 ตัวนั้นมาทำเป็น matrix 
      3x3 และ transport และหาเลขอยู่ตำแหน่งที่ (2,2)


**Quiz1**

จงเขียน array ที่มีแต่เลข 0 แบบ vector 10 ตัว และ แบบ Matrix 4x4

In [0]:
#run this cell first.
import numpy as np
import random

In [0]:
#Quiz1
print(np.zeros(10))
print(np.zeros((4,4)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Quiz2**

จงเขียน array ที่มีแต่เลข 1 แบบ vector 5 ตัว และ แบบ Matrix 3x3

In [0]:
#Quiz2
print(np.ones(5))
print(np.ones((3,3)))

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**Quiz3**

จงเขียน array ที่มีเป็นการ random ตัวเลข 20 ตัว แบบ float ค่าอยู่ในช่วง 10-99 แล้วนำแต่ละเลขยกกำลังสอง

In [33]:
#Quiz3
#test
rand_id1 = np.random.uniform(10,100,20)
print('Random 20 numbers between 10 and 99\n',rand_id1)
print('Then power of 2!\n',rand_id1**2)

Random 20 numbers between 10 and 99
 [80.59422824 31.91214393 66.83840975 44.74371363 20.09628557 69.80145105
 91.0896967  28.24413137 33.95819725 85.47090264 76.22851334 57.53837388
 82.86449829 15.59566516 85.27242036 41.46969777 24.98594898 88.6774883
 60.96552916 76.63057781]
Then power of 2!
 [6495.42962489 1018.38493028 4467.37301768 2001.99990905  403.86069365
 4872.24256866 8297.33284574  797.73095702 1153.15916077 7305.27519768
 5810.78624556 3310.66446923 6866.52507731  243.2247718  7271.38567417
 1719.73583299  624.29764668 7863.6969318  3716.79574529 5872.24545497]


In [5]:
#Quiz3
x, y = 10, 99
rand20 = (np.random.rand(20)*(y-x)) + x
power2 = rand20 ** 2
print('Random 20 numbers between 10 and 99\n',rand20)
print('Then power of 2!\n',power2)

Random 20 numbers between 10 and 99
 [33.50362632 41.3039099  58.60449497 35.77145477 90.52483258 74.05057647
 98.70658265 41.40788944 77.31012226 51.81193913 20.43541012 23.48749463
 67.63313745 15.95030317 88.95546559 70.24215277 65.68888474 22.25248814
 29.24229663 14.50813361]
Then power of 2!
 [1122.49297661 1706.01297319 3434.48683084 1279.59697641 8194.74531297
 5483.48787518 9742.98945924 1714.61330785 5976.85500381 2684.47703668
  417.60598684  551.66240401 4574.24128193  254.41217115 7913.07485889
 4933.96002563 4315.02957796  495.17322827  855.11191214  210.48594074]


**Quiz4**

ทำเหมือนข้อ 3 แต่เขียนแบบ List comprehension

In [0]:
import array as arr

In [70]:
#Quiz4
rand_lst = []
for i in range(20):
    x = random.uniform(10,100)
    rand_lst.append(x)
y = arr.array('d',rand_lst)
power_2 = [i**2 for i in y]

print('Random 20 numbers between 10 and 99\n',list(y))
print('Then power of 2!\n',power_2)

Random 20 numbers between 10 and 99
 [52.70200431493495, 27.36311463533096, 98.60823141329236, 94.45692310905007, 13.215932854891491, 70.73580700903833, 31.368030132034036, 19.236351869084384, 87.21198131729712, 93.0874733924627, 39.247847032946154, 64.83384972494089, 37.138246033948185, 53.08677467287653, 35.138225296613484, 15.689654598740482, 56.84223743862394, 40.01142155051076, 45.89139585834525, 47.02561039135864]
Then power of 2!
 [2777.5012588114223, 748.7400425462633, 9723.583302457419, 8922.110323228997, 174.66088122500037, 5003.554393219915, 983.9533143641952, 370.03723323122625, 7605.929685288581, 8665.277702592452, 1540.3934967215403, 4203.428070156218, 1379.249318478068, 2818.205645168765, 1234.6948769955677, 246.16526142777835, 3231.039957028901, 1600.913854492677, 2106.0202138273476, 2211.4080326798576]


In [49]:
#test
rand_lst2 = np.random.uniform(10,100,20)
power_2 = [i**2 for i in rand_lst2]

print('Random 20 numbers between 10 and 99\n',rand_lst2)
print('Then power of 2!\n',power_2)


Random 20 numbers between 10 and 99
 [52.44027037 37.53286109 13.46652399 47.36304194 88.34374435 92.2708094
 98.68479504 64.85738523 56.48267243 86.1661702  32.59087126 14.93592569
 10.50218181 35.64923408 38.72449765 50.71802949 58.08278835 88.87419911
 49.25504947 20.44413292]
Then power of 2!
 [2749.9819563452734, 1408.715661634146, 181.34726837864406, 2243.257741730497, 7804.617165524886, 8513.902267046746, 9738.688772857075, 4206.480419039017, 3190.2922845405947, 7424.608887235089, 1062.1648894339357, 223.08187610521261, 110.2958226917081, 1270.8678904743865, 1499.5867181557107, 2572.318515564471, 3373.6103020567953, 7898.623267958072, 2426.059897918432, 417.9625707205596]


 **Quiz5**

 นำข้อ 3 และ 4 มาเปรียบเวลากัน โดยใช้ฟังก์ชั่น time.time( ) เพื่อจับเวลา แสดงผลลัพธ์ในรูปแบบมิลลิวินาที

In [74]:
#Quiz5

#checking time from Quiz3
x, y = 10, 99
rand20_power2 = ((np.random.rand(20)*(y-x)) + x) ** 2 
%timeit -n1000 rand20_power2 


#checking time from Quiz4
#Quiz4
rand_lst = []
for i in range(20):
    x = random.uniform(10,100)
    rand_lst.append(x)
y = arr.array('d',rand_lst)
power_2 = [i**2 for i in list(y)]

%timeit -n1000 power_2


1000 loops, best of 3: 17.9 ns per loop
1000 loops, best of 3: 20.2 ns per loop
