#To-do
9. จงสร้าง identity matrix แบบ 4x4

10. จงหาว่า array ที่มีสมาชิก 100 ตัว เริ่มจาก 5 ถึง 25 มีผลต่างแต่ละตัวเท่ากับเท่าใด

11. จงเขียนฟังก์ชั่น random ตัวเลขแบบ float ในช่วง 0-1 ขึ้นมา 1 ตัว

12. จงเขียนฟังก์ชั่นที่ random ตัวเลขแบบ int ในช่วง 50-100 โดยให้อยู่ในรูป Matrix 4x4 และ Transpose

13. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 8,9,13,14 

14. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 18,19,20

15. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกเฉพาะ 16,17,21,22

16. ให้ array ที่กำหนด จงเขียนโค้ดที่เลือกทั้งแถว 3

17. จงเขียนโค้ดที่ทำให้ได้ array นี้ออกมา

18. จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ If-else เช็คทีละตัวว่าตัวใดบ้างที่มีค่ามากกว่า
      50 และปริ้นออกมา

19. จงเขียนโปรแกรมสุ่มเลขจำนวนเต็มในช่วง 10-100 ออกมาอยู่ใน matrix 5x5 และใช้ conditional selection เช็คว่าตัวใดบ้างมีค่า  
      มากกว่า 40 นำมาใส่ List ที่สร้างใหม่ และปริ้นออกมา

20. เขียนโปรแกรมรับค่าจากผู้ใช้ให้ป้อนเลข 9 ตัว แต่ละตัวต้องไม่ซ้ำกันและมีค่าอยู่ในช่วง 10-100 นำเลข 9 ตัวนั้นมาทำเป็น matrix 
      3x3 และ transport และหาเลขอยู่ตำแหน่งที่ (2,2)


**Quiz1**

จงเขียน array ที่มีแต่เลข 0 แบบ vector 10 ตัว และ แบบ Matrix 4x4

In [0]:
#run this cell first.
import numpy as np
import random
import array as arr
import time

In [0]:
#Quiz1
print(np.zeros(10))
print(np.zeros((4,4)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Quiz2**

จงเขียน array ที่มีแต่เลข 1 แบบ vector 5 ตัว และ แบบ Matrix 3x3

In [0]:
#Quiz2
print(np.ones(5))
print(np.ones((3,3)))

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**Quiz3**

จงเขียน array ที่มีเป็นการ random ตัวเลข 20 ตัว แบบ float ค่าอยู่ในช่วง 10-99 แล้วนำแต่ละเลขยกกำลังสอง

In [0]:
#Quiz3
#test
rand_id1 = np.random.uniform(10,100,20)
print('Random 20 numbers between 10 and 99\n',rand_id1)
print('Then power of 2!\n',rand_id1**2)

Random 20 numbers between 10 and 99
 [80.59422824 31.91214393 66.83840975 44.74371363 20.09628557 69.80145105
 91.0896967  28.24413137 33.95819725 85.47090264 76.22851334 57.53837388
 82.86449829 15.59566516 85.27242036 41.46969777 24.98594898 88.6774883
 60.96552916 76.63057781]
Then power of 2!
 [6495.42962489 1018.38493028 4467.37301768 2001.99990905  403.86069365
 4872.24256866 8297.33284574  797.73095702 1153.15916077 7305.27519768
 5810.78624556 3310.66446923 6866.52507731  243.2247718  7271.38567417
 1719.73583299  624.29764668 7863.6969318  3716.79574529 5872.24545497]


In [0]:
#Quiz3
x, y = 10, 99
rand20 = (np.random.rand(20)*(y-x)) + x
power2 = rand20 ** 2
print('Random 20 numbers between 10 and 99\n',rand20)
print('Then power of 2!\n',power2)

Random 20 numbers between 10 and 99
 [33.50362632 41.3039099  58.60449497 35.77145477 90.52483258 74.05057647
 98.70658265 41.40788944 77.31012226 51.81193913 20.43541012 23.48749463
 67.63313745 15.95030317 88.95546559 70.24215277 65.68888474 22.25248814
 29.24229663 14.50813361]
Then power of 2!
 [1122.49297661 1706.01297319 3434.48683084 1279.59697641 8194.74531297
 5483.48787518 9742.98945924 1714.61330785 5976.85500381 2684.47703668
  417.60598684  551.66240401 4574.24128193  254.41217115 7913.07485889
 4933.96002563 4315.02957796  495.17322827  855.11191214  210.48594074]


**Quiz4**

ทำเหมือนข้อ 3 แต่เขียนแบบ List comprehension

In [0]:
import array as arr

In [0]:
#Quiz4
y = arr.array('d',y)
for i in range(20):
    x = random.uniform(10,100)
    y.append(x)

power_2 = [i**2 for i in list(y)]


print('Random 20 numbers between 10 and 99\n',list(y))
print('Then power of 2!\n',power_2)

Random 20 numbers between 10 and 99
 [19.626477962231434, 87.56838894481565, 88.3087982364212, 75.5891053234267, 80.60035247377908, 61.33638451313613, 37.10267745729315, 84.53512973241975, 62.46343206412966, 78.13927364899867, 31.97912396021241, 14.493892940998851, 24.251337641173937, 14.25529948133352, 62.507006131515595, 41.91301108888742, 69.56532040849625, 82.3902749299846, 43.94509794596, 75.48481706540575, 29.50535882709552, 97.19654943591718, 54.05235560136243, 65.14883690127743, 83.08407100819952, 96.03530829962492, 86.48763665325971, 15.15501172069802, 54.47520433299122, 34.615581097374985, 96.35812553806394, 68.95414868578443, 31.461141045655754, 99.99083395435629, 59.333748338629654, 76.59189087468711, 12.01357332162786, 78.38216310177533, 61.579372804696845, 61.408527379301596, 86.87563006630265, 67.43013530110824, 54.86105938040572, 16.72354441818836, 57.97276724169218, 93.7601058526969, 80.30729924913268, 40.148896096023265, 86.05422435319299, 54.08774837661395, 92.007281

In [0]:
#test
rand_lst2 = np.random.uniform(10,100,20)
power_2 = [i**2 for i in rand_lst2]

print('Random 20 numbers between 10 and 99\n',rand_lst2)
print('Then power of 2!\n',power_2)


Random 20 numbers between 10 and 99
 [52.44027037 37.53286109 13.46652399 47.36304194 88.34374435 92.2708094
 98.68479504 64.85738523 56.48267243 86.1661702  32.59087126 14.93592569
 10.50218181 35.64923408 38.72449765 50.71802949 58.08278835 88.87419911
 49.25504947 20.44413292]
Then power of 2!
 [2749.9819563452734, 1408.715661634146, 181.34726837864406, 2243.257741730497, 7804.617165524886, 8513.902267046746, 9738.688772857075, 4206.480419039017, 3190.2922845405947, 7424.608887235089, 1062.1648894339357, 223.08187610521261, 110.2958226917081, 1270.8678904743865, 1499.5867181557107, 2572.318515564471, 3373.6103020567953, 7898.623267958072, 2426.059897918432, 417.9625707205596]


 **Quiz5**

 นำข้อ 3 และ 4 มาเปรียบเวลากัน โดยใช้ฟังก์ชั่น time.time( ) เพื่อจับเวลา แสดงผลลัพธ์ในรูปแบบมิลลิวินาที

In [0]:
import time

In [64]:
#Quiz5

#checking time from Quiz3
x, y = 10, 99
rand20_power2 = (np.random.rand(20)*(y-x)) + x
time1 = time.time() * 1000
power2 = rand20_power2 ** 2
time2 = time.time() * 1000
print(time2-time1)

#test
#%timeit -n100000 rand20_power2 
#millis1 = int(time.time() * 1000)
#print(millis1)

0.06787109375


In [63]:
#checking time from Quiz4
#Quiz4
y = []
y = arr.array('d',y)
for i in range(20):
    x = random.uniform(10,100)
    y.append(x)
time1 = time.time() * 1000
power_2 = [i**2 for i in list(y)]
time2 = time.time() * 1000
print(time2-time1)

#test
#%timeit -n100000 power_2
#millis2 = int(time.time() * 1000)
#print(millis1)
#print(millis2)
#print('Compare between Quiz3 {} and Quiz4 {} diff = '.format(millis1,millis2),millis1-millis2)

0.102783203125


**Quiz6**

จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลข 10 ถึง 1000  

In [48]:
arr2 = np.arange(10,1001)
print(arr2)
print(arr2.shape)

[  10   11   12   13   14   15   16   17   18   19   20   21   22   23
   24   25   26   27   28   29   30   31   32   33   34   35   36   37
   38   39   40   41   42   43   44   45   46   47   48   49   50   51
   52   53   54   55   56   57   58   59   60   61   62   63   64   65
   66   67   68   69   70   71   72   73   74   75   76   77   78   79
   80   81   82   83   84   85   86   87   88   89   90   91   92   93
   94   95   96   97   98   99  100  101  102  103  104  105  106  107
  108  109  110  111  112  113  114  115  116  117  118  119  120  121
  122  123  124  125  126  127  128  129  130  131  132  133  134  135
  136  137  138  139  140  141  142  143  144  145  146  147  148  149
  150  151  152  153  154  155  156  157  158  159  160  161  162  163
  164  165  166  167  168  169  170  171  172  173  174  175  176  177
  178  179  180  181  182  183  184  185  186  187  188  189  190  191
  192  193  194  195  196  197  198  199  200  201  202  203  204  205
  206 

**Quiz7**

จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคู่ 10 ถึง 2000

In [50]:
arr2 = np.arange(10,1001,2)
print(arr2)
print(arr2.shape)

[  10   12   14   16   18   20   22   24   26   28   30   32   34   36
   38   40   42   44   46   48   50   52   54   56   58   60   62   64
   66   68   70   72   74   76   78   80   82   84   86   88   90   92
   94   96   98  100  102  104  106  108  110  112  114  116  118  120
  122  124  126  128  130  132  134  136  138  140  142  144  146  148
  150  152  154  156  158  160  162  164  166  168  170  172  174  176
  178  180  182  184  186  188  190  192  194  196  198  200  202  204
  206  208  210  212  214  216  218  220  222  224  226  228  230  232
  234  236  238  240  242  244  246  248  250  252  254  256  258  260
  262  264  266  268  270  272  274  276  278  280  282  284  286  288
  290  292  294  296  298  300  302  304  306  308  310  312  314  316
  318  320  322  324  326  328  330  332  334  336  338  340  342  344
  346  348  350  352  354  356  358  360  362  364  366  368  370  372
  374  376  378  380  382  384  386  388  390  392  394  396  398  400
  402 

**Quiz8**

จงเขียน array ที่ใช้ฟังก์ชั่นใน numpy ได้เลขคี่ 12 ถึง 900

In [52]:
arr2 = np.arange(12,901,3)
print(arr2)
print(arr2.shape)

[ 12  15  18  21  24  27  30  33  36  39  42  45  48  51  54  57  60  63
  66  69  72  75  78  81  84  87  90  93  96  99 102 105 108 111 114 117
 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171
 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216 219 222 225
 228 231 234 237 240 243 246 249 252 255 258 261 264 267 270 273 276 279
 282 285 288 291 294 297 300 303 306 309 312 315 318 321 324 327 330 333
 336 339 342 345 348 351 354 357 360 363 366 369 372 375 378 381 384 387
 390 393 396 399 402 405 408 411 414 417 420 423 426 429 432 435 438 441
 444 447 450 453 456 459 462 465 468 471 474 477 480 483 486 489 492 495
 498 501 504 507 510 513 516 519 522 525 528 531 534 537 540 543 546 549
 552 555 558 561 564 567 570 573 576 579 582 585 588 591 594 597 600 603
 606 609 612 615 618 621 624 627 630 633 636 639 642 645 648 651 654 657
 660 663 666 669 672 675 678 681 684 687 690 693 696 699 702 705 708 711
 714 717 720 723 726 729 732 735 738 741 744 747 75